---
title: "Blog"
format: html
---

Blog Post 1 \| What does a scientist actually do? \| 18-03-2026

In Jeff Leek's *How To Be A Modern Scientist*, some of the mysticism revolving around the responsibilities of the contemporary scientific thinker was dispelled for me, in addition to some of the anxiety regarding how to begin the journey to becoming one. For a long time I thought of science as only taking place in obscure academic corners accessible only to the top thinkers in each field (as measured by the number of publications they can point to). I also had little clue as to what differentiated a 'real' scientist from someone who is merely competent enough to use the internet or some other seemingly credible source when communicating new or innovative ideas. When we see 'representatives' of science in fictional media, none of the daily effort and practice required to become someone capable of contributing original knowledge is ever shown. Jeff Leek's work revealed to me that good scientific inquiry is carried out in many deceptively simple but powerful forms: blog posts, social media, and reproducible and open-source code are all increasingly necessary avenues for scientific thinkers to grow an audience and establish their work. Carrying out these kinds of duties is what separates the modern scientist from the more isolated view of the scientist I held. In terms of small actionable steps for actually growing into the role of the modern scientist, two points that stuck out to me as being immediately actionable were creating publication-ready plots as the first-step for any future writing, and to take advantage of pre-print websites to avoid the frustrating timelines involved when attempting to write a paper. Both of these are going to be steps I take for my work in the Wilson lab at Case, for when we have optimized an assay and solution for the neonatal small analyte testing we are working on.
